### ISSUE TITLE
Order of scan is wrong

### ISSUE THREAD

**Issue by CallMeChin** [NanoSmasher/aether-gazer-scans-ocr#2]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MYUSER~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MYUSER~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

2023/09/10 11:09 | [Functor] | Elf - Maeglin | 3 | 4 | 4
-- | -- | -- | -- | -- | --
2023/09/10 11:20 | [Character] | Shinku - Buzenbo Tengu | 4 | 5 | 5
2023/09/10 11:26 | [Functor] | Elf - Maeglin | 3 | 1 | 6
2023/09/10 11:35 | [Functor] | Synchronic - Pingala | 3 | 2 | 7
2023/09/10 11:56 | [Functor] | Elf - Maeglin | 3 | 3 | 8
2023/09/10 11:56 | [Functor] | Elf - Maeglin | 3 | 4 | 9
2023/09/10 11:56 | [Character] | Rahu - Asura | 5 | 5 | 10
2023/09/10 03:04 | [Functor] | Shikigami - Kerakeraonna | 3 | 6 | 1
2023/09/10 03:10 | [Character] | New Pact - Verthandi | 3 | 7 | 2
2023/09/10 03:23 | [Character] | Surefire - Zenkibo Tengu | 3 | 8 | 3
2023/09/10 03:37 | [Functor] | Herald - Hippo | 3 | 9 | 4
2023/09/10 04:04 | [Character] | Radiant Feather - Hera | 4 | 10 | 5
2023/09/10 04:04 | [Character] | Puppet Master - Hades | 5 | 1 | 6
2023/09/10 04:48 | [Functor] | Shikigami - Kerakeraonna | 3 | 2 | 1
2023/09/10 04:59 | [Functor] | Herald - Hippo | 3 | 3 | 2
2023/09/10 05:00 | [Functor] | Shikigami - Kerakeraonna | 3 | 4 | 3
2023/09/10 10:48 | [Functor] | EIf - Maeglin | 3 | 5 | 4
2023/09/10 02:15 | [Functor] | Herald - Hippo | 3 | 6 | 5
2023/09/10 02:16 | [Functor] | Shikigami - Kerakeraonna | 3 | 7 | 6
2023/09/10 02:16 | [Functor] | Herald - Hippo | 3 | 8 | 7
2023/09/10 02:16 | [Functor] | Elf - Maeglin | 3 | 9 | 8
2023/09/10 03:01 | [Functor] | Synchronic - Pingala | 3 | 10 | 9

</body>

</html>

**Comment by NanoSmasher** [comment]
By default, I have entries added in chronological order, with the oldest summon at the top of the generated spreadsheet. This simplifies adding new entries to an existing list.
